version: '3'

services:
  sandboxtown-front:
    build:
      # context是Dockerfile文件中的上下文路径，一般是Dockerfile所在的目录
      context: sandbox_town_frontend
    ports:
      - "443:443"
    # 如果你需要使用HTTPS，那么你需要将下面的注释取消掉
    # volumes:
    #   # 本地的证书文件挂载到容器内部
    #   # 你需要将路径替换为你自己的证书路径
    #   - /path/to/your/cert.pem:/etc/nginx/ssl/cert.pem
    #   - /path/to/your/key.pem:/etc/nginx/ssl/key.pem
    restart: unless-stopped

  sandboxtown-back:
    build:
      context: sandbox_town_backend
    expose:
      # Spring Boot 服务在 Docker 内部网络上暴露 9090 端口，但不暴露到宿主机
      # 但其实这里不写也可以，只是为了更清晰
      - "9090" 
    restart: unless-stopped
    # 限制内存，JVM 可以自动识别 Docker 容器的内存限制，并据此设置默认的内存使用
    mem_limit: 300m

  sandboxtown-mysql:
    # image: mysql:8.1
    # mariadb相比mysql更节约内存，并且兼容mysql，并且默认使用utf8mb4
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sandbox_town
    volumes:
      - ./sandbox_town_db/customer.cnf:/etc/mysql/conf.d/customer.cnf
      # 将MySQL的数据文件挂载到命名卷，以便数据持久化
      # 如果卷不存在，会自动创建
      # 如果卷存在，会使用卷中的数据文件
      - sandboxtown-db-volume:/var/lib/mysql
      # 初始化数据库时执行的SQL脚本
      # 注意：如果/var/lib/mysql目录中已经存在数据文件，那么这个SQL脚本不会被执行
      - ./sandbox_town_db/import.sql:/docker-entrypoint-initdb.d/import.sql
    restart: unless-stopped
    # 限制内存，MySQL/MariaDB 的某些配置项会根据内存大小自动调整
    mem_limit: 70m
    
  sandboxtown-redis:
    image: redis:7.2-alpine
    environment:
      REDIS_PASSWORD: 123456
    restart: unless-stopped

volumes:
  sandboxtown-db-volume:
    driver: local
