version: '3'

services:
  sandboxtown-front:
    build:
      # context是Dockerfile文件中的上下文路径，一般是Dockerfile所在的目录
      context: sandbox_town_frontend
      # Dockerfile路径
      # 如果你在开发过程中，需要频繁修改源代码，那么可以使用Dockerfile2
      # 在你使用Dockerfile2的同时，需要挂载数据卷./sandbox_town_frontend:/app，另外如果你不使用Linux，宿主机和docker之间的IO特别慢，可以使用命名卷替代目录挂载
      dockerfile: Dockerfile
    ports:
      - "80:80"
    # 如果你需要使用HTTPS，那么你需要将上面的port设置替换为下述内容
    # ports:
    #   - "443:443"
    # volumes:
    #   # 本地的证书文件挂载到容器内部
    #   # 你需要将路径替换为你自己的证书路径
    #   - /path/to/your/cert.pem:/etc/nginx/ssl/cert.pem
    #   - /path/to/your/key.pem:/etc/nginx/ssl/key.pem
    restart: unless-stopped
      
  sandboxtown-back:
    build:
      context: sandbox_town_backend
      # Dockerfile路径
      # 如果你在开发过程中，需要频繁修改源代码，那么可以使用Dockerfile2，它会将你编译好的文件挂载到容器中
      dockerfile: Dockerfile
    # 如果你在开发过程中，需要测试swagger，那么暴露后端端口
    ports:
      - "9090:9090"
    restart: unless-stopped
    # 限制内存，JVM 可以自动识别 Docker 容器的内存限制，并据此设置默认的内存使用
    mem_limit: 300m
    volumes:
      - sanboxtown-user-upload:/userUpload
    environment:
      - REDIS_PASSWORD=123456
      - MYSQL_PASSWORD=root

  sandboxtown-mysql:
    # image: mysql:8.1
    # mariadb相比mysql更节约内存，并且兼容mysql，并且默认使用utf8mb4
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sandbox_town
    volumes:
      - ./sandbox_town_db/customer.cnf:/etc/mysql/conf.d/customer.cnf
      # 将MySQL的数据文件挂载到命名卷，以便数据持久化
      # 如果卷不存在，会自动创建
      # 如果卷存在，会使用卷中的数据文件
      - sandboxtown-db-volume:/var/lib/mysql
      # 初始化数据库时执行的SQL脚本
      # 注意：如果/var/lib/mysql目录中已经存在数据文件，那么这个SQL脚本不会被执行
      - ./sandbox_town_db/import.sql:/docker-entrypoint-initdb.d/import.sql
    restart: unless-stopped
    # 限制内存，MySQL/MariaDB 的某些配置项会根据内存大小自动调整
    mem_limit: 70m
    # 如果测试需要，可以将MySQL的端口暴露到宿主机，取消下面的注释
    # ports:
    #   - "3306:3306"
    
  sandboxtown-redis:
    image: redis:7.2-alpine
    environment:
      REDIS_PASSWORD: 123456
    restart: unless-stopped
    volumes:
      - sandboxtown-redis-data:/data
    # 如果测试需要，可以将Redis的端口暴露到宿主机，取消下面的注释
    # ports:
    #   - "6379:6379"

volumes:
  sandboxtown-db-volume:
    driver: local
  sandboxtown-redis-data:
    driver: local
  sanboxtown-user-upload:
    driver: local
