version: '3'

services:
  vue-app:
    build:
      context: ./path-to-vue-project
      dockerfile: Dockerfile
    ports:
      - "80:80"

  springboot-app:
    build:
      context: ./path-to-springboot-project
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/yourdbname
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
      - SPRING_REDIS_HOST=redis

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: yourdbname
    volumes:
      - ./path-to-import.sql:/docker-entrypoint-initdb.d/import.sql

  redis:
    image: redis:alpine

