version: '3'

services:
  sandboxtownfront:
    build:
      context: ..
      dockerfile: ./deploy/vue/Dockerfile
    ports:
      - "445:443"

  # sandboxtownback:
  #   build:
  #     context: ..
  #     dockerfile: ./deploy/springboot/Dockerfile
  #   expose:
  #     # Spring Boot 服务在 Docker 内部网络上暴露 9090 端口，但不暴露到宿主机
  #     - "9090" 
  #   environment:
  #     - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/yourdbname
  #     - SPRING_DATASOURCE_USERNAME=root
  #     - SPRING_DATASOURCE_PASSWORD=rootpassword
  #     - SPRING_REDIS_HOST=redis

  # sandboxtownmysql:
  #   image: mysql:8.1
  #   environment:
  #     MYSQL_ROOT_PASSWORD: rootpassword
  #     MYSQL_DATABASE: yourdbname
  #   volumes:
  #     - ./path-to-import.sql:/docker-entrypoint-initdb.d/import.sql

  # sandboxtownredis:
  #   image: redis:7.2-alpine

