version: '3'

services:
  sandboxtownfront:
    build:
      context: ..
      # dockerfile的路径相对于context，而非docker-compose.yml
      dockerfile: ./deploy/vue/Dockerfile
    ports:
      - "443:443"
    volumes:
      - /path/to/your/cert.pem:/etc/nginx/ssl/cert.pem
      - /path/to/your/key.pem:/etc/nginx/ssl/key.pem
    restart: unless-stopped

  sandboxtownback:
    build:
      context: ..
      dockerfile: ./deploy/springboot/Dockerfile
    expose:
      # Spring Boot 服务在 Docker 内部网络上暴露 9090 端口，但不暴露到宿主机
      # 但其实这里不写也可以，只是为了更清晰
      - "9090" 
    restart: unless-stopped
    # 限制内存，JVM 可以自动识别 Docker 容器的内存限制，并据此设置默认的内存使用
    mem_limit: 300m

  sandboxtownmysql:
    # image: mysql:8.1
    # mariadb相比mysql更节约内存，并且兼容mysql，并且默认使用utf8mb4
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sandbox_town
    volumes:
      - ../sandbox_town_backend/import.sql:/docker-entrypoint-initdb.d/import.sql
      - ./mysql/customer.cnf:/etc/mysql/conf.d/customer.cnf
    restart: unless-stopped
    # 限制内存，MySQL/MariaDB 的某些配置项会根据内存大小自动调整
    mem_limit: 70m
    
  sandboxtownredis:
    image: redis:7.2-alpine
    environment:
      REDIS_PASSWORD: 123456
    restart: unless-stopped

