server:
  port: 9090
  servlet:
    context-path: /

spring:
  redis:
    host: localhost
    port: 6379
    password: 123456
    # redis有16个数据库，默认使用0号数据库
    database: 0
    lettuce:
      pool:
        max-idle: 16
        max-active: 32
        min-idle: 8
