mapId: "1"
# 用户上传文件的路径，原先我放resources/static目录下，后来了解到该目录主要用于存储应用的静态资源
userUploadPath: "/userUpload/"

server:
  port: 9090
  tomcat:
    threads:
      max: 20 # Maximum amount of worker threads.
      min-spare: 1 # Minimum amount of worker threads
  servlet:
    context-path: /

spring:
  redis:
    host: sandboxtown-redis
    port: 6379
    password: ${REDIS_PASSWORD}
    # redis有16个数据库，默认使用0号数据库
    database: 0
    lettuce:
      # redis连接池配置
      pool:
        max-idle: 16 # Maximum number of "idle" connections in the pool
        max-active: 32 # Maximum number of connections
        min-idle: 1 # minimum number of idle connections
  datasource:
    url: jdbc:mysql://sandboxtown-mysql:3306/sandbox_town?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: ${MYSQL_PASSWORD}
    # 数据库连接池配置
    hikari:
      # 连接池的最大连接数
      maximum-pool-size: 30
      # 连接池的最小空闲连接数
      minimum-idle: 1

mybatis-plus:
  configuration:
    # 将数据库的下划线命令转换为Java的驼峰命名
    map-underscore-to-camel-case: true
    # 配置打印sql语句
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


logging:
  level:
    root: info
